elasticsearch:
  container_name: elasticsearch
  build: elasticsearch/
  volumes:
    - /Users/chris/fucknuts:/fuckingfucknuts

logstash:
  container_name: logstash
  build: logstash/
  links:
    - elasticsearch

kibana:
  container_name: kibana
  build: kibana/
  ports:
    - 8080:80
    - 29001:9001
  links:
    - elasticsearch
