elk_storage:
  container_name: elk_storage
  build: elk_storage/

elasticsearch:
  container_name: elasticsearch
  build: elasticsearch/
  volumes:
    - /var/lib/docker/data/elasticsearch/var/log/elasticsearch:/var/log/elasticsearch
    - /var/lib/docker/data/elasticsearch/var/lib/elasticsearch:/var/lib/elasticsearch
  volumes_from:
    - elk_storage

logstash:
  container_name: logstash
  build: logstash/
  links:
    - elasticsearch
  external_links:
    - redis

kibana:
  container_name: kibana
  build: kibana/
  ports:
    - 8080:80
    - 29001:9001
  links:
    - elasticsearch
