elasticsearch:
  container_name: elasticsearch
  build: elasticsearch/
  volumes_from:
    - elk_storage

logstash:
  container_name: logstash
  build: logstash/
  links:
    - elasticsearch

kibana:
  container_name: kibana
  build: kibana/
  ports:
    - 8080:80
    - 29001:9001
  links:
    - elasticsearch

elk_storage:
  container_name: elk_storage
  build: elk_storage/
