FROM ubuntu:14.04.3

RUN mkdir -p /var/lib/docker/data/elasticsearch/var/log/elasticsearch
RUN mkdir -p /var/lib/docker/data/elasticsearch/var/lib/elasticsearch

VOLUME /var/lib/docker/data/elasticsearch/var/log/elasticsearch
VOLUME /var/lib/docker/data/elasticsearch/var/lib/elasticsearch

CMD ["true"]
